### ISSUE TITLE
[Bug]: Rename, Duplicate, Move prompt not cleared before displaying messages

### ISSUE THREAD

**Issue by star-szr** [chrisgrieser/nvim-genghis#25] opened 2023-08-21 14:23 UTC
### Bug Description

After running, rename, duplicate, or move, you are prompted to enter the new filename/path.

Once the operation completes, there is a success message, but the success message is displayed immediately after the filename/path prompt. I would expect to only see the success message at this point.

Example, when renaming:

`Rename File to: test-newRenamed "test.lua" as "test-new.lua".`

### Relevant Screenshot

![image](https://github.com/chrisgrieser/nvim-genghis/assets/327943/202e9452-e4ff-4169-af02-3c622b165058)

### To Reproduce

1. Run `:New`
2. Enter `test.lua`
3. Run `:Rename`
4. Type in a new name for the file.
5. Press `<CR>`

I tested with a clean configuration with only this plugin installed and was still able to reproduce the behaviour described.

### neovim version

```Text
0.9.1
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment] 2023-09-09 21:57
Sorry, whatever I tried, I cannot reproduce the issue? 

Have you maybe been using an outdated version of the plugin? As far as I can tell, [this line here](https://github.com/chrisgrieser/nvim-genghis/blob/main/lua/genghis.lua#L65) should prevent such issues and was merged a few weeks ago

**Closed** 2023-09-10 10:35 UTC
Labels: bug
